// ============================================================
// FILE: main.dart
// PURPOSE: The entry point of your Flutter application.
//
// CONCEPTS TAUGHT:
//   - main(): Every Dart program starts here. Flutter's main() calls
//     runApp() to inflate the widget tree and start rendering.
//
//   - WidgetsFlutterBinding.ensureInitialized(): Must be called before
//     runApp() if you do ANY async work in main() (like loading
//     preferences, initializing Firebase, etc.). It sets up the bridge
//     between Flutter's framework and the platform (iOS/Android/Web).
//     Even though we don't need it yet, it's good practice to include
//     it from the start - forgetting it later causes cryptic errors.
//
//   - ProviderScope: The ROOT of Riverpod's dependency injection tree.
//     Every Riverpod provider in your app lives inside this scope.
//     It MUST wrap your entire app (be the outermost widget).
//     Think of it as: "Everything inside this scope can use Riverpod."
//
//     Without ProviderScope, calling ref.watch() or ref.read() anywhere
//     in your app would throw an error.
//
// ARCHITECTURE DECISION:
//   main.dart is kept minimal on purpose. Its only job is:
//   1. Initialize bindings
//   2. Wrap the app in ProviderScope
//   3. Launch the app widget
//   All configuration (theme, routing, etc.) lives in app.dart.
// ============================================================

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:unisalle/app.dart';
import 'package:unisalle/firebase_options.dart';

void main() async {
  // Ensure Flutter's engine is ready before any async work.
  // Required when calling async code before runApp() (e.g. Firebase.initializeApp).
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase using the platform-specific options generated by
  // `flutterfire configure` (lib/firebase_options.dart).
  // Must run before any Firebase service or google_sign_in is used.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // ProviderScope is the root of Riverpod's dependency injection tree.
  // Every provider in the app lives inside this scope.
  runApp(
    const ProviderScope(
      child: UnisalleApp(),
    ),
  );
}
